#!/usr/bin/env python3
"""Emit ggml/src/gqh-tables.h from the authoritative geo-quant reference.

The GQH decode must be bit-exact against geoquant/formats/gqh.py, so every
constant the kernel uses is generated by *calling that reference*, never by
re-deriving it in C (powf/geomspace would drift by an ULP).

usage: <geo-quant .venv python> gen_gqh_tables.py <path/to/geo-quant-repo> [out.h]
"""
import struct
import sys
from pathlib import Path

import numpy as np
import torch

repo = Path(sys.argv[1]).resolve()
out = Path(sys.argv[2]) if len(sys.argv) > 2 else \
    Path(__file__).resolve().parents[2] / "ggml/src/gqh-tables.h"
sys.path.insert(0, str(repo))
from geoquant.formats import gqh  # noqa: E402


def bits(v):
    return struct.unpack("<I", struct.pack("<f", np.float32(v)))[0]


def table(name, rows, per_row, comment):
    """Emit a NAME_INIT initialiser macro plus a host `static const` array.

    Two forms because the same numbers are needed in more than one place: the CPU
    decoder and the CUDA host code read the plain arrays, while the device wants
    the E4M3 LUT and the gqh2_c codebook in __constant__ memory. One source, no drift.
    """
    body = []
    for i, row in enumerate(rows):
        vals = ", ".join(f"0x{bits(v):08x}u" for v in row)
        pretty = ", ".join(f"{float(np.float32(v)):+.9g}" for v in row)
        body.append(f"    {{ {vals} }}, /* [{i:2d}] {pretty} */")
    macro = f"#define {name}_INIT {{ \\\n" + " \\\n".join(body) + " \\\n}"
    return (f"// {comment}\n{macro}\n"
            f"static const uint32_t {name}[{len(rows)}][{per_row}] = {name}_INIT;")


# --- E4M3 (torch float8_e4m3fn) decode LUT, all 256 byte values -------------
e4m3 = torch.arange(256, dtype=torch.uint8).view(torch.float8_e4m3fn).float().numpy()

# --- gqh3: 12 gamma codes -> 8 sorted grid levels ---------------------------
grid3 = [gqh._grid3(float(g)) for g in gqh.GAMMA_GRID]
assert len(gqh.GAMMA_GRID) == 12

# --- gqh2_h: 12 a codes -> 4 grid levels {-1,-a,+a,+1} ----------------------
grid2 = [np.array([-1.0, -float(a), float(a), 1.0], np.float32) for a in gqh.A_GRID]
assert len(gqh.A_GRID) == 12

# --- gqh2_c: frozen (256,8) codebook + 128-entry even-parity sign table -----
cb = gqh._codebook().astype(np.float32)
signs, _ = gqh._sign_tables()
signs = np.asarray(signs).astype(np.uint8).reshape(-1)
assert cb.shape == (256, 8), cb.shape
assert signs.shape == (128,), signs.shape

src = f'''#pragma once
// GENERATED by scripts/gqh/gen_gqh_tables.py -- do not edit by hand.
//
// Bit-exact constants for the GQH (Geo-Quant Hierarchical) decode, lifted
// straight out of geoquant/formats/gqh.py. Values are stored as raw float32
// bit patterns so the compiler cannot re-round them; recomputing e.g.
// powf(k/4, gamma) on device drifts by an ULP and breaks bit-exact parity.
//
// reference: gqh._e4m3_decode, gqh._grid3/GAMMA_GRID, gqh.A_GRID,
//            gqh._codebook, gqh._sign_tables
// torch {torch.__version__}, numpy {np.__version__}

#include <stdint.h>

// Layout constants, read from the reference module so they cannot be hand-copied wrong.
#define GQH_SUPERBLOCK   {gqh.SUPERBLOCK}  // weights per superblock (row/input axis)
#define GQH_SUBBLOCK      {gqh.SUBBLOCK}  // weights per sub-block
#define GQH_N_SUB         {gqh.N_SUB}  // sub-blocks per superblock
#define GQH_RATIO_MAX     {gqh.RATIO_MAX}  // uint4 sub-block ratio denominator
#define GQH_HEADER_BYTES   {gqh.TENSOR_HEADER}  // per-tensor: float32 tensor_scale + uint8 grid code
#define GQH3_SB_BYTES    {gqh.SB_BYTES_3}
#define GQH2H_SB_BYTES    {gqh.SB_BYTES}
#define GQH2C_SB_BYTES    {gqh.GQH2C_BYTES_PER_SB}
#define GQH_GRID_CODES    {len(gqh.GAMMA_GRID)}  // GAMMA_GRID / A_GRID length
#define GQH2C_GROUP        {gqh.CB_GROUP}  // weights per codebook group
#define GQH2C_BLOCK       {gqh.C_BLOCK}  // weights per gqh2_c scale block
#define GQH2C_BLOCKS_PER_SB {gqh.C_BLOCKS_PER_SB}
#define GQH2C_GROUPS_PER_BLOCK {gqh.C_GROUPS_PER_BLOCK}

{table("GQH_E4M3_LUT", [e4m3[i:i+8] for i in range(0, 256, 8)], 8,
       "torch.float8_e4m3fn -> float32, indexed [byte>>3][byte&7]. 0x7f/0xff are NaN.")}

{table("GQH_RATIO_Q", [[np.float32(r) / np.float32(gqh.RATIO_MAX)] for r in range(16)], 1,
       "uint4 sub-block ratio -> ratio/15 in float32 (single-rounded, as numpy does it)")}

{table("GQH3_GRID", grid3, 8,
       "gqh3: GAMMA_GRID[code] -> _grid3(gamma), 8 levels sorted ascending")}

{table("GQH2H_GRID", grid2, 4,
       "gqh2_h: A_GRID[code] -> {-1, -a, +a, +1}")}

{table("GQH2C_CODEBOOK", cb, 8,
       "gqh2_c: frozen (256,8) codebook, gqh._codebook()")}

// gqh2_c: 7-bit sign index -> 8-bit even-parity mask (bit e set => element e negative)
#define GQH2C_SIGN_MASK_INIT {{ \\
{(" \\" + chr(10)).join("    " + ", ".join(f"0x{v:02x}" for v in signs[i:i+16]) + ","
                        for i in range(0, 128, 16))} \\
}}
static const uint8_t GQH2C_SIGN_MASK[128] = GQH2C_SIGN_MASK_INIT;
'''
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(src)
print(f"wrote {out} ({len(src)} bytes)")
